### ISSUE TITLE
feat: add option for get gate with default value

### ISSUE THREAD

**Issue by liran2000** [statsig-io/java-server-sdk#22]
\* similar to [GO sdk issue](https://github.com/statsig-io/go-sdk/issues/32)

Background
In continue of [OpenFeature PR](https://github.com/open-feature/java-sdk-contrib/pull/641), it is a common practice to evaluate a boolean/gate with a default value:
```
client.getBooleanValue("non-existing", true)
```

### Problem
BooleanEvaluation with default value true cannot fallback to true.
On scenarios such as get gate of non-existing gate, statsig returns false without indication of whether it was successful get gate or some error reason. Therefore, the evaluation will be evaluated to false in this case.

### Suggested solution
add:
```
Statsig.checkGateAsync(user, key, boolean fallback);
```

@xinlili-statsig

**Comment by weihao-statsig** [comment]
We've added a new API(which will return the evaluation details regarding a gate) for this.  Please take a look. https://github.com/statsig-io/java-server-sdk/releases/tag/v1.14.0

**Comment by liran2000** [comment]
> We've added a new API(which will return the evaluation details regarding a gate) for this. Please take a look. https://github.com/statsig-io/java-server-sdk/releases/tag/v1.14.0

Thanks. The request of fallback was not added exactly as requested, so managed to overcome it via [specific reasons check](https://github.com/open-feature/java-sdk-contrib/pull/722/files#diff-b85bb4536d5afd0710d15085c3cbeea7e1db1eceeebf595c6c9b6a283b569a19R122).
