### ISSUE TITLE
feat: add option to fetch multiple layers at once

### ISSUE THREAD

**Issue by vignesh-sc** [statsig-io/java-server-sdk#23]
**Current Implementation**
The current api `statsigServer.getLayerSync(user, layerName, new GetLayerOptions())` allows pulling one layer at a time

**Problem**
In an api server, it is sometimes beneficial to fetch multiple layers at once and add them to the request context. So that it is can be easily used in different api handlers.

**Solution**
Add an api to fetch multiple layers at once ex: `statsigServer.getLayersSync`

**Comment by tore-statsig** [comment]
It should be easy enough to write a method that takes in an array of layer names, and returns the layers for each of those - I dont think the SDK needs to add support for this as a top level API as you can currently compose the exposed API into this type of method if you need it.

It also seems like you might be overfetching data in some cases and want to leave the layer fetching to the particular callsite, adding caching for that if there are multiple callsites.  Again, all implementation details for your own webserver.
