### ISSUE TITLE
[SDK Feature Request] Interface to register callback on an interested feature gate, possible enhancement to `RulesUpdatedCallback` ?

### ISSUE THREAD

**Issue by anunay98** [statsig-io/java-server-sdk#24]
Hi,

Can we have an interface that enables SDK adopters to register callback on a specific feature gate? Currently the `RulesUpdatedCallback` is a functional interface that gets the details of all the feature gates even when only some might have changed.

Thanks,
Anunay

**Comment by tore-statsig** [comment]
Thanks for the request!  I think this will be a longer term item for us, but we do plan to get to this functionality later (subscribe to gate change)
