### ISSUE TITLE
`downloadConfigSpecs()` shall only parse the response on success

### ISSUE THREAD

**Issue by mangatmodi** [statsig-io/java-server-sdk#26]
In [downloadConfigSpecs()downloadConfigSpecs()](https://github.com/statsig-io/java-server-sdk/blob/b0bacb7d5f50cc66c9be7158b690c59ceb45498d/src/main/kotlin/com/statsig/sdk/SpecStore.kt#L493) I got HTTP 401 response as
```
Response{protocol=h2, code=401, message=, url=https://api.statsigcdn.com/v1/download_config_specs/api-key.json?sinceTime=0}
``` 

Here the `message` field is an empty string, but gson will try to parse it and produce an exception as 
```
[Statsig]: An exception was caught:  com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected 
BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

This doesn't tell much information to the user. Instead response code should be checked and a better exception should be thrown as
```
[Statsig]: An exception was caught:  HTTP Response 401 returned from server
```

Infact it would be even better to get some stacktrace.

Its a follow-up from https://github.com/statsig-io/java-server-sdk/issues/25

**Comment by tore-statsig** [comment]
Thanks for the report, we will look into improving that
