### ISSUE TITLE
Leak in OkHttpClient while connecting to https://statsigapi.net

### ISSUE THREAD

**Issue by udi-agr** [statsig-io/java-server-sdk#31]
java-server-sdk version used 1.16.0

I am getting the following log from time to time - 
**A connection to https://statsigapi.net/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);**

I checked the closed/open issues but couldn't find anything related to this, i am assuming this should be an known issue is it fixed somewhere will bumping the library version help ?

**Comment by weihao-statsig** [comment]
Hi @udi-agr Thanks for flagging, This is a known issue and it has already got resolved in https://github.com/statsig-io/java-server-sdk/releases/tag/1.27.1

Please try bump the version and let me know if this is still exist.

**Comment by udi-agr** [comment]
Hi @weihao-statsig - Thanks for confirming, i have updated to 1.32.0 will monitor now.

**Comment by udi-agr** [comment]
Hi @weihao-statsig - with 1.32.0 i think i am not getting the mentioned error but i have started seeing this "**2024-10-24T20:53:30.605Z WARN [Statsig] Failed to download config specification, HTTP Response 401 received from server**"

I am wondering why is this coming, is this coming while internally statsig tries to get the rules every x seconds based on rulesSetsSyncIntervalMs ? There is way too much occurence of this..

**Comment by weihao-statsig** [comment]
Yeah it should be come from whenever the background threads trying to fetch rule sets and then if the response is not successful, then you will get this kind of warning.

it might be due to the server outage. There's a issue ongoing rn. This might be related. https://status.statsig.com/

**Comment by weihao-statsig** [comment]
Closed for now since the primary issue has been resolved, feel free to reach out if you found anything else @udi-agr
